apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-04-10T12:35:07Z
  labels:
    app: helloworld
  name: helloworld
  namespace: default
  resourceVersion: "11180"
  selfLink: /api/v1/namespaces/default/services/helloworld
  uid: 12f3dcdb-5b8d-11e9-83b0-42010a800015
spec:
  clusterIP: 10.11.240.79
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30677
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
